X_INCDIRS	:= xlibc/include/ xtk/ libpng/ jpeg/ zlib/ gato/include/ uview/include/

X_CFLAGS	:= -fno-builtin -w -fno-PIE -m32 -fno-stack-protector -std=gnu99 -O3

SRC			:= image/ render/

TARGET_TYPE	:= static
NAME		:= gato