X_INCDIRS	:= xlibc/include/ libpng/ jpeg/ zlib/

X_INCDIRS		+= 	freetype/include \
				freetype/src/autofit \
				freetype/src/base \
				freetype/src/cache \
				freetype/src/cff \
				freetype/src/cid \
				freetype/src/gxvalid \
				freetype/src/otvalid \
				freetype/src/pfr \
				freetype/src/psaux \
				freetype/src/pshinter \
				freetype/src/psnames \
				freetype/src/raster \
				freetype/src/sfnt \
				freetype/src/smooth \
				freetype/src/truetype \
				freetype/src/type1 \
				freetype/src/type42 \
				freetype/src/winfonts

SRC			:=	src/autofit/ \
				src/base/ \
				src/cache/ \
				src/cff/ \
				src/cid/ \
				src/gxvalid/ \
				src/otvalid/ \
				src/pfr/ \
				src/psaux/ \
				src/pshinter/ \
				src/psnames/ \
				src/raster/ \
				src/sfnt/ \
				src/smooth/ \
				src/truetype/ \
				src/type1/ \
				src/type42/ \
				src/winfonts/

TARGET_TYPE	:= static
NAME		:= freetype