X_INCDIRS	:= xlibc/include/ libpng/ jpeg/ zlib/
X_INCDIRS	+= libwebp/

SRC			:= src/dec/*.c \
			src/demux/*.c \
			src/dsp/*.c \
			src/enc/*.c \
			src/mux/*.c \
			src/utils/*.c

TARGET_TYPE	:= static
NAME		:= webp