/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEBUG 0

#undef FRIBIDI_NO_DEPRECATED

#define HAVE_MEMMOVE

#define HAVE_MEMORY_H 1

#define HAVE_MEMSET

#define HAVE_STDLIB_H 1

#define HAVE_STRDUP

#define HAVE_STRINGIZE 1

#define HAVE_STRING_H 1

#define HAVE_SYS_TIMES_H

#define STDC_HEADERS 1

#define SIZEOF_INT sizeof(int)

# define FRIBIDI "fribidi"
# define FRIBIDI_NAME "fribidi"
# define FRIBIDI_VERSION "1.0.10"
# define FRIBIDI_BUGREPORT "unknown"
# define FRIBIDI_INTERFACE_VERSION_STRING "unknown"

#include <stdbool.h>
#include <string.h>
