X_INCDIRS	:= xlibc/include \
			xtk \
			uview/include \
			dotfont \
			sdl2/SDL2 \
			libwebp/src \
			libtiff \

X_INCDIRS	+= jpeg \
			libzlib \
			libpng \
			freetype/include \

SRC			:= *.c

TARGET_TYPE	:= static
NAME		:= SDL2_ttf
