X_INCDIRS	:= xlibc/include pthread/include
X_INCDIRS	+= sdl2/include

X_CFLAGS	+= -D__XBOOK
SRC	:= \
	src/*.c \
	src/audio/*.c \
	src/audio/dummy/*.c \
	src/cpuinfo/*.c \
	src/events/*.c \
	src/file/*.c \
	src/haptic/*.c \
	src/haptic/dummy/*.c \
	src/joystick/*.c \
	src/joystick/dummy/*.c \
	src/loadso/dummy/*.c \
	src/power/*.c \
	src/filesystem/dummy/*.c \
	src/render/*.c \
	src/render/software/*.c \
	src/sensor/*.c \
	src/sensor/dummy/*.c \
	src/stdlib/*.c \
	src/thread/*.c \
	src/thread/generic/*.c \
	src/timer/*.c \
	src/timer/dummy/*.c \
	src/video/*.c \
	src/video/dummy/*.c \

TARGET_TYPE	:= static
NAME		:= sdl