sinclude ../scripts/env.mk
sinclude ../scripts/localenv.mk

X_ASFLAGS	:= $(ENV_AFLAGS)
X_CFLAGS	:= $(ENV_CFLAGS)

X_LDFLAGS	:= $(ENV_LDFLAGS)

LD			:=  $(ENV_LD)
AS			:= $(ENV_AS)

export AS LD

MODULE		:= xlibc
MODULE		+= xlibcpp
MODULE		+= sconf
MODULE		+= pthread
MODULE		+= zlib
MODULE		+= libtiff
MODULE		+= libwebp
MODULE		+= netsocket
MODULE		+= jpeg
MODULE		+= libpng
MODULE		+= lvgl
MODULE		+= uview
MODULE		+= xtk
MODULE		+= gato
MODULE		+= freetype
MODULE		+= pixman
MODULE		+= cairo
MODULE		+= fribidi
MODULE		+= sdl2
MODULE		+= lua
MODULE		+= SDL2_image
MODULE		+= SDL2_ttf
MODULE		+= iniparser
MODULE		+= cjson
